---

# Playbook: Desktop Configuration
#
# Description:
#   This playbook is designed to preserve the state of my desktop environment
#   by automating various configuration tasks using Ansible roles.
#
# Author: Jacob Benison
#
# Version: 0.2.0
#
# Usage: ansible-playbook -i inventory.yml main.yml
#
# Notes: 
#   - Ensure that the vars.yml file contains necessary variables before running
#     the playbook.
#   - Uses role-based organization following Ansible best practices

- name: Configure Desktop Environment
  hosts: localhost
  become: false
  

  roles:
    - role: system
      tags: ['system', 'base']
    
    - role: desktop
      tags: ['desktop', 'ui']
    
    - role: terminal
      tags: ['terminal', 'shell']
    
    - role: development
      tags: ['development', 'dev', 'docker']
    
    - role: multimedia
      tags: ['multimedia', 'apps', 'office', 'social', 'graphics']