# Community packages

- name: Install language tools available in community packages
  become: yes
  community.general.pacman:
    name:
      - dart
      - go
      - nodejs
      - npm
      - opam
      - python-pip
      - python-pipx
      - python-poetry
    state: present

# pnpm

- name: Check if pnpm has been installed
  command: pnpm --version
  register: pnpm_check
  ignore_errors: true

- name: Download and install pnpm
  shell: curl -fsSL https://get.pnpm.io/install.sh | sh -
  args:
    executable: /bin/bash
  when: pnpm_check.failed

# Rust

- name: Check if Rust has been installed
  command: rustc --version
  register: rust_check
  ignore_errors: true

- name: Install Rust if not present
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    executable: /bin/bash
  when: rust_check.failed

# Ocaml Platform Tools

- name: Chif if opam is initialized
  stat:
    path: "/home/{{ username }}/.opam"
  register: opam_init_check

- name: Initialize opam if necessary
  shell: |
    opam init -y
    $eval $(opam env)
  when: not opam_init_check.stat.exists

- name: Check if odoc is installed
  command: opam list --installed odoc
  register: odoc_check
  ignore_errors: true

- name: Installed odoc is not present
  shell: opam install odoc
  args:
    executable: /bin/bash
  when: odoc_check.failed

- name: Check if ocamlformat is installed
  command: opam list --installed ocamlformat
  register: ocamlformat_check
  ignore_errors: true

- name: Installed ocamlformat is not present
  shell: opam install ocamlformat
  args:
    executable: /bin/bash
  when: ocamlformat_check.failed

- name: Check if utop is installed
  command: opam list --installed utop
  register: utop_check
  ignore_errors: true

- name: Installed utop is not present
  shell: opam install utop
  args:
    executable: /bin/bash
  when: utop_check.failed

# Test browsers

- name: Install browsers available community packages
  become: yes
  community.general.pacman:
    name:
      - firefox-developer-edition
      - torbrowser-launcher
      - chromium
    state: present

# I prefer to handle AUR packages manually. I'll install other browsers for
# testing manually.
