# Create home/usr directories 
- name: Check existence of Projects directory
  stat: 
    path: /home/{{ username }}/Projects
  register: projects_dir

- name: Create Projects directory if it doesn't exist
  ansible.builtin.file:
    path: /home/{{ username }}/Projects
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0775'
  become: yes
  when: not projects_dir.stat.exists

- name: Check existence of Documents directory
  stat: 
    path: /home/{{ username }}/Documents
  register: docs_dir

- name: Create Documents directory if it doesn't exist
  ansible.builtin.file:
    path: /home/{{ username }}/Documents
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0775'
  become: yes
  when: not docs_dir.stat.exists

- name: Check existence of Downloads directory
  stat: 
    path: /home/{{ username }}/Downloads
  register: downloads_dir

- name: Create Downloads directory if it doesn't exist
  ansible.builtin.file:
    path: /home/{{ username }}/Downloads
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0775'
  become: yes
  when: not downloads_dir.stat.exists

- name: Check existence of Desktop directory
  stat: 
    path: /home/{{ username }}/Desktop
  register: desktop_dir

- name: Create Desktop directory if it doesn't exist
  ansible.builtin.file:
    path: /home/{{ username }}/Desktop
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0775'
  become: yes
  when: not desktop_dir.stat.exists
