
[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "None"
decorations = "full"
opacity = 0.9
blur = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono NFM", style = "Regular" }
size = 11
builtin_box_drawing = true

[colors.primary]
background = "#15131A"
foreground = "#dcd7ba"

[colors.normal]
black = "#15131A"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
magenta = "#957fb8"
cyan = "#6a9589"
white = "#c8c093"

[colors.bright]
black = "#727169"
red = "#e82424"
green = "#98bb6c"
yellow = "#e6c384"
blue = "#7fb4ca"
magenta = "#938aa9"
cyan = "#7aa89f"
white = "#dcd7ba"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[general]
live_config_reload = true
# Alacritty  TOML configuration

import = []

[terminal]
