# .bashrc
- name: Use keychain .bashrc
  blockinfile:
    dest: /home/{{ username }}/.bashrc
    marker: '# {mark} use keychain to manage ssh keys'
    insertafter: EOF
    create: yes 
    block: |
      eval $(keychain --eval --quiet id_ed25519)
