- name: Install gtk apps
  community.general.pacman:
    name:
      - arc-solid-gtk-theme
      - keepassxc
      - lxappearance
      - pcmanfm
      - qt5ct
    state: present

# - name: Remove any .profile in ~/.profile
#   ansible.builtin.file:
#     path: /home/{{ username }}/.profile
#     state: absent

- name: Creating a symlink from repo `.profile` to `~/`
  ansible.builtin.file:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/roles/common/files/user_home/.profile
    dest: /home/{{ username }}/.profile
    state: link
