# Create home/usr directories 
- name: Create 'Projects' directory
  ansible.builtin.file:
    path: /home/{{ username }}/Projects
    state: directory
    mode: '0775'

- name: Create 'Documents' directory
  ansible.builtin.file:
    path: /home/{{ username }}/Documents
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0775'

- name: Create 'Downloads' directory
  ansible.builtin.file:
    path: /home/{{ username }}/Downloads
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0775'

- name: Create 'Desktop' directory
  ansible.builtin.file:
    path: /home/{{ username }}/Desktop
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0775'
