# - name: Remove any i3 config in ~/.config
#   ansible.builtin.file:
#     path: /home/{{ username }}/.config/i3
#     state: absent

- name: Creating a symlink from repo `i3` to `~/.config`
  ansible.builtin.file:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/roles/common/files/user_home/i3/
    dest: /home/{{ username }}/.config/i3
    state: link

# - name: Remove any i3status config
#   ansible.builtin.file:
#    path: /home/{{ username }}/.config/i3status
#    state: absent

- name: Creating a symlink from repo `i3status` to `~/.config`
  ansible.builtin.file:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/roles/common/files/user_home/i3status/
    dest: /home/{{ username }}/.config/i3status
    state: link
