# Determine if a path exists and is a directory.
- name: Get stats of ~/.config/i3
  ansible.builtin.stat:
    path: /home/{{ username }}/.config/i3
  register: p

- name: Remove any kitty config that is not a symlink
  ansible.builtin.file:
    path: /home/{{ username }}/.config/i3
    state: absent
  when: p.stat.isdir is defined and p.stat.isdir

- name: Creating a symlink from repo `i3` to `~/.config`
  ansible.builtin.file:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/roles/common/files/user_home/i3/
    dest: /home/{{ username }}/.config/i3
    state: link

# Determine if a path exists and is a directory.
- name: Get stats of ~/.config/i3status
  ansible.builtin.stat:
    path: /home/{{ username }}/.config/i3status
  register: p

- name: Remove any kitty config that is not a symlink
  ansible.builtin.file:
    path: /home/{{ username }}/.config/i3status
    state: absent
  when: p.stat.isdir is defined and p.stat.isdir

- name: Creating a symlink from repo `i3status` to `~/.config`
  ansible.builtin.file:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/roles/common/files/user_home/i3status/
    dest: /home/{{ username }}/.config/i3status
    state: link
