# sudo cp -r ./backgrounds/* /usr/share/backgrounds/
- name: Copy background images
  copy:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/images/backgrounds/
    dest: /usr/share/backgrounds/
    force: False
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rw,g+r,o--

# sudo cp -r ./pixmaps/* /usr/share/pixmaps/
- name: Copy pixmaps
  copy:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/images/pixmaps/
    dest: /usr/share/pixmaps/
    force: False
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rw,g+r,o--

- name: Install lightdm greeter
  community.general.pacman:
    name:
      - lightdm-webkit2-greeter
    state: present

# Update main lightdm conf
- name: Switch to lightdm-webkit2-greeter
  replace:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#greeter-session=example-gtk-gnome$'
    replace: 'greeter-session=lightdm-webkit2-greeter'

# Update main lightdm conf
- name: Set user-session to i3
  replace:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#user-session=default$'
    replace: 'user-session=i3'

# Update greeter logo
- name: Set greeter logo
  replace:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    regexp: '^logo\s{1,}= /usr/share/pixmaps/archlinux-logo.svg$'
    replace: 'logo = /usr/share/pixmaps/archlinux-logo.png'

# Update settings in greeter
- name: Set greeter user_image
  replace:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    regexp: '^user_image\s{1,}= /usr/share/pixmaps/archlinux-user.svg$'
    replace: 'user_image = /usr/share/pixmaps/ge.png'
