- name: Install lightdm greeter
  community.general.pacman:
    name:
      - lightdm-webkit2-greeter
    state: present

# sudo cp -r ./backgrounds/* /usr/share/backgrounds/
- name: Copy background images
  copy:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/images/backgrounds/
    dest: /usr/share/backgrounds/
    force: False
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rw,g+r,o--

# sudo cp -r ./pixmaps/* /usr/share/pixmaps/
- name: Copy pixmaps
  copy:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/images/pixmaps/
    dest: /usr/share/pixmaps/
    force: False
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rw,g+r,o--

- name: Get sha1sum of lightdm config in etc
  stat:
    path: /etc/lightdm/lightdm.conf
    checksum_algorithm: sha256
    get_checksum: yes
  register: sha_etc

- name: Get sha1sum of lightdm config in user_module
  stat:
    path: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/roles/common/files/user_home/lightdm/lightdm.conf
    checksum_algorithm: sha256
    get_checksum: yes
  register: sha_new

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/lightdm/lightdm.conf
    state: absent
  when: sha_etc != sha_new

- name: Replace lightdm config
  copy:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/roles/common/files/user_home/lightdm/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    force: False
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rw,g+r,o--

- name: Get sha1sum of lightdm config in etc
  stat:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    checksum_algorithm: sha256
    get_checksum: yes
  register: sha_default

- name: Get sha1sum of lightdm config in user_module
  stat:
    path: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/roles/common/files/user_home/lightdm/lightdm-webkit2-greeter.conf
    checksum_algorithm: sha256
    get_checksum: yes
  register: sha_custom

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    state: absent
  when: sha_default != sha_custom

- name: Replace lightdm-webkit2-greeter config
  copy:
    src: /home/{{ username }}/Projects/dotfiles/bijiben/ansible/roles/common/files/user_home/lightdm/lightdm-webkit2-greeter.conf
    dest: /etc/lightdm/lightdm-webkit2-greeter.conf
    force: False
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rw,g+r,o--
