- name: check updates
  pacman:
    update_cache: yes
    upgrade: yes

# Configure pacman (colorize and repos)
- include_tasks: pacman.yml

# SSH Keys (uncomment here and ansible/roles/main.yml)
# - include_tasks: ssh_key.yml

# bash
- include_tasks: bash.yml

# Switch CapsLock to Esc
- include_tasks: keymap.yml

# Create directories in /home/usr
- include_tasks: home_directories.yml

# Setup powermanagement
- include_tasks: power_management.yml

# Install core apps
- include_tasks: core_apps.yml

# Configure convenient USB mounting
- include_tasks: usb.yml

# Copy i3 config
- include_tasks: i3.yml

# Copy kitty config
- include_tasks: kitty.yml

# Setup Neovim config
- include_tasks: nvim.yml

# Configure lightdm
- include_tasks: lightdm.yml

# Setup GTK apps
- include_tasks: gtk.yml

# Install and setup office related packages
- include_tasks: office.yml

# Setup AUR
- include_tasks: aur.yml
  when: use_aur == True
