- name: Install home office apps
  community.general.pacman:
    name: 
      # Social
      - telegram-desktop
      # Word processing
      - libreoffice-fresh
      # email client
      - evolution 
      # for printers # https://www.youtube.com/watch?v=jnmCbEWNV1w
      - cups
      - system-config-printer
      - gutenprint
    state: present

- name: start/enable cups
  ansible.builtin.systemd:
    name: cups
    state: started
    enabled: true

- name: adding existing user "{{ username }}" to group sudo
  ansible.builtin.user:
    name: "{{ username }}"
    groups: wheel,lp
    append: yes
