# TODO: Read the manual
# - [ ] [Power Management](https://wiki.archlinux.org/title/Power_management)
#   - [ ] [Suspend_and_hibernate](https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate)
# - [ ] [CPU Frequency](https://wiki.archlinux.org/title/CPU_frequency_scaling)
# - [ ] [Laptop Power Management](https://wiki.archlinux.org/title/Laptop)
#
# Install packages
- name: Install packages for power management
  community.general.pacman:
    name:
      - i3lock
      - xss-lock 

- name: Copy energy preference config file
  copy: 
   src: user_home/energy_performance_preference.conf
   dest: /etc/tmpfiles.d/energy_performance_preference.conf
   force: False
   owner: "{{ username }}"
   group: "{{ username }}"
   mode: u+rw,g+r,o--

- name: Copy audio power saving preferences config file
  copy: 
   src: user_home/audio_powersave.conf
   dest: /etc/modprobe.d/audio_powersave.conf
   force: False
   owner: "{{ username }}"
   group: "{{ username }}"
   mode: u+rw,g+r,o--

- name: Copy virtual memory writeback time preferences config file
  copy: 
   src: user_home/dirty.conf
   dest: /etc/sysctl.d/dirty.conf
   force: False
   owner: "{{ username }}"
   group: "{{ username }}"
   mode: u+rw,g+r,o--

- name: Copy laptop knob preferences config file
  copy: 
   src: user_home/laptop.conf
   dest: /etc/sysctl.d/laptop.conf
   force: False
   owner: "{{ username }}"
   group: "{{ username }}"
   mode: u+rw,g+r,o--
