# TODO: Read the manual
# - [ ] [Power Management](https://wiki.archlinux.org/title/Power_management)
#   - [ ] [Suspend_and_hibernate](https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate)
# - [ ] [CPU Frequency](https://wiki.archlinux.org/title/CPU_frequency_scaling)
# - [ ] [Laptop Power Management](https://wiki.archlinux.org/title/Laptop)
#
# Install packages
- name: Install packages for power management
  community.general.pacman:
    name:
      - i3lock
      - xss-lock 
