# SSH Keys, Agent, Client and Keyring
#
# - [Wiki](https://wiki.archlinux.org/title/SSH_keys#SSH_agents) 

- name: Install SSH key related packages
  community.general.pacman:
    name:
      - openssh
      - keychain
    state: present

- name: Create '.ssh' directory
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
    force: false

- name: Generate an OpenSSH keypair ed25519 and encrypted private key
  community.crypto.openssh_keypair:
    path: /home/{{ username }}/.ssh/id_ed25519
    type: ed25519
    owner: "{{ username }}"
    group: "{{ username }}"
    passphrase: "{{ ssh_passphrase }}"
