# .bashrc

# - name: Example inserting a new block into ~/.bashrc
#   blockinfile:
#     dest: /home/{{ username }}/.bashrc
#     marker: '# {mark} description'
#     insertafter: EOF
#     create: yes 
#     block: |
#       alias=abc="echo 'Hello, World!'"
