- name: Install Docker and Docker Compose
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: start/enable docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

# https://docs.docker.com/engine/install/linux-postinstall/
- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the user  with a bash shell, appending the group "docker" to the user's group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: yes
