- name: Install gtk apps
  community.general.pacman:
    name:
      - arc-solid-gtk-theme
      - keepassxc
      - lxappearance
      - pcmanfm
      - qt5ct
    state: present
      
# Determine if a path exists and is a directory.
- name: Get stats of ~/.profile
  ansible.builtin.stat:
    path: /home/{{ username }}/.profile
  register: p

- name: Remove any .profile config that is not a symlink
  ansible.builtin.file:
    path: /home/{{ username }}/.profile
    state: absent
  when: p.stat.isfile is defined and p.stat.isfile

# Create a symlink
- name: Creating a symlink from repo `.profile` to `~/`
  ansible.builtin.file:
    src: /home/{{ username }}/Projects/dotfiles/main/roles/common/files/user_home/.profile
    dest: /home/{{ username }}/.profile
    state: link

