# SSH Keys, Agent, Client and Keyring
#
# - [Wiki](https://wiki.archlinux.org/title/SSH_keys#SSH_agents) 

- name: Install SSH key related packages
  community.general.pacman:
    name:
      - openssh
      - keychain
    state: present

- name: Create '.ssh' directory
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
    force: false
